[project]
name = "ollama-ui"
version = "1.0.0"
description = "ollama interface built with streamlit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["ollama>=0.4.7", "streamlit>=1.43.0"]
